stages:
  - build

.cabal_build: &cabal_script

ghc7103_cabal:
  image: haskell:7.10.3
  stage: build
  before_script:
    - cabal sandbox init
    - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
    - cabal --version
    - cabal update
    - cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O1 --reorder-goals --max-backjumps=-1
    - echo "Installed dependencies"
  script:
    - cabal configure --enable-tests --enable-benchmarks --enable-coverage -v2 --ghc-options="-Werror"
    - cabal build
    - cabal test --show-details=streaming
    - cabal sdist
    - cabal copy
    - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
    - stack install hpc-coveralls
    - stack exec hpc-coveralls --exclude-dir=test test doctest
  cache:
    paths:
      - .cabal-sandbox/
      - cabal.sandbox.config

stack:
  image: fpco/stack-build
  stage: build
  before_script:
    - stack --no-terminal --install-ghc test --only-dependencies
  script:
    - stack --no-terminal $ARGS test --coverage --haddock --no-haddock-deps
    - curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.3.0/shc-linux-x64-$GHCVER.tar.bz2 | tar -xj
    - ./shc orbit test doctest
  cache:
    paths:
    - $HOME/.ghc/
    - $HOME/.cabal/
    - $HOME/.stack/

nix_unstable_7103:
  image: nixos/nix
  stage: build
  before_script:
    - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    - nix-channel --update
    - export NIX_PATH=nixpkgs=$HOME/.nix-defexpr/channels/nixpkgs
  script:
    - 'nix-build -E ''with (import <nixpkgs> {}); (haskell.packages.ghc7103.callPackage ./. {}).overrideDerivation (oldAttrs: { checkPhase = "runHook preCheck; ./Setup test --show-details=streaming; runHook postCheck;";})'''
